### PR TITLE
fix: parameter issues for deleteNamespacedSecret

### PR DESCRIPTION
**Pull request by djach7**
Swaps parameters for the deleteNamespacedSecret function. Parameters were previously passed backwards (namespace, secret name) which was causing the function to fail and crash the application when executed. Parameters are now passed correctly (secret name, namespace) to rectify this issue.

### CODE REVIEW

**Comment by djach7** [comment]
Hey @tumido, I goofed up my commits I apologize. The only change I was trying to make is the one that's in there now, flipping the parameters on deleteNamespacedSecret. It should be good for an actual review now, I apologize again for the slow turn around and the confusion.

**Comment by djach7** [comment]
I just updated this pr with the changes we implemented to fix the getNamespace issues we had when using it outside the cluster. If you'd like these changes in a totally separate pr just let me know.

**Comment by guymguym** [comment]
@tumido I can't see the logs on the failed test. Do you understand what is the failure?

**Comment by tumido** [comment]
@djach7 seems like you have some weird EOLs in the commit. I've tried to fix it, but I can't push to your fork. Try running `pre-commit run -a` locally to fix the file (and then commit those changes).

**Review by tumido — COMMENTED** [review]
/lgtm
/approve

**Review by tumido — APPROVED** [review]

**Pull request merged**
